config/routes.rb
Rails.application.routes.draw do
  resources :rides

end

app/models/ride.rb
class Ride < ActiveRecord::Base
    validates :origin, :destination, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]

  # GET /rides
  # GET /rides.json
  def index
    @rides = Ride.all
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
  end

  # GET /rides/new
  def new
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit
  end

  # POST /rides
  # POST /rides.json
  def create
    @ride = Ride.new(ride_params)

    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ride_params
      params.require(:ride).permit(:origin, :destination)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taxi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rides/_form.html.erb
<%= form_for(@ride) do |f| %>
  <% if @ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% @ride.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rides/edit.html.erb
<h1>Editing Ride</h1>

<%= render 'form' %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rides</h1>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>Destination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rides.each do |ride| %>
      <tr>
        <td><%= ride.origin %></td>
        <td><%= ride.destination %></td>
        <td><%= link_to 'Show', ride %></td>
        <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
        <td><%= link_to 'Destroy', ride, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ride', new_ride_path %>

app/views/rides/new.html.erb
<h1>New Ride</h1>

<%= render 'form' %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @ride.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @ride.destination %>
</p>

<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>